/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.shapetowerdefense;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author behnf
 */
public class GamePanel extends javax.swing.JPanel {

    private ArrayList<ShapeCharacter> playerUnits;
    private ArrayList<Enemy> enemies;
    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
        this.playerUnits = new ArrayList<>();
        this.enemies = new ArrayList<>();
    }

    public void addPlayerUnit(ShapeCharacter unit) {
        playerUnits.add(unit);
    }

    public void addEnemy(Enemy enemy) {
        enemies.add(enemy);
    }

    public void update() {
        // Move units
//        for (ShapeCharacter unit : playerUnits) unit.moveForward();
//        for (Enemy enemy : enemies) enemy.moveForward();
//
//       
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        // Draw player units
        for (ShapeCharacter unit : playerUnits) {
            g.setColor(Color.BLUE);
            if (unit.shapeType.equals("Circle")) {
                g.fillOval(unit.getX(), unit.getY(), unit.width, unit.height);
            } else {
                g.fillRect(unit.getX(), unit.getY(), unit.width, unit.height);
            }
        }

        // Draw enemies
        for (Enemy enemy : enemies) {
            g.setColor(Color.RED);
            if (enemy.shapeType.equals("Circle")) {
                g.fillOval(enemy.getX(), enemy.getY(), enemy.width, enemy.height);
            } else {
                g.fillRect(enemy.getX(), enemy.getY(), enemy.width, enemy.height);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
